### ISSUE TITLE
`ChunkCompressionThread` deletes chunks instead of compressing them

### ISSUE THREAD

**Issue by Vladg24YT** [Vladg24YT/LilyBukkit#18]
**Log**:
```
2022-07-17 13:46:10 [SEVERE] java.lang.NullPointerException: Cannot read the array length because "b" is null
2022-07-17 13:46:10 [SEVERE]    at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:431)
2022-07-17 13:46:10 [SEVERE]    at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
2022-07-17 13:46:10 [SEVERE]    at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035)
2022-07-17 13:46:10 [SEVERE]    at java.base/java.io.DataOutputStream.write(DataOutputStream.java:112)
2022-07-17 13:46:10 [SEVERE]    at net.minecraft.src.Packet51MapChunk.writePacket(Packet51MapChunk.java:85)
2022-07-17 13:46:10 [SEVERE]    at net.minecraft.src.Packet.writePacket(Packet.java:101)
2022-07-17 13:46:10 [SEVERE]    at net.minecraft.src.NetworkManager.sendPacket(NetworkManager.java:102)
2022-07-17 13:46:10 [SEVERE]    at net.minecraft.src.NetworkManager.sendNetworkPacket(NetworkManager.java:209)
2022-07-17 13:46:10 [SEVERE]    at net.minecraft.src.NetworkWriterThread.run(NetworkWriterThread.java:17)
```

**Comment by Vladg24YT** [comment]
Will revert to vanilla Lilypad compression.
