### ISSUE TITLE
Offline mode completely prevents clients from connecting to the server

### ISSUE THREAD

**Issue by Vladg24YT** [Vladg24YT/LilyBukkit#23]
**Log (client was previously authenticated)**:
```
2022-07-23 13:54:03 [INFO] MATCH ULPP1

2022-07-23 13:54:03 [INFO] EXT NAME ULPP VER 1

2022-07-23 13:54:03 [INFO] MATCH ROSE1

2022-07-23 13:54:03 [INFO] EXT NAME ROSE VER 1

2022-07-23 13:54:03 [INFO] MATCH ULPP1

2022-07-23 13:54:03 [INFO] EXT NAME ULPP VER 1

2022-07-23 13:54:03 [INFO] MATCH ROSE1

2022-07-23 13:54:03 [INFO] EXT NAME ROSE VER 1

2022-07-23 13:54:03 [INFO] MATCH ULPP1

2022-07-23 13:54:03 [INFO] EXT NAME ULPP VER 1

2022-07-23 13:54:03 [INFO] MATCH ROSE1

2022-07-23 13:54:03 [INFO] EXT NAME ROSE VER 1

2022-07-23 13:54:03 [INFO] Disconnecting Vladg24 [/25.19.133.219:35690]: This user is authenticated! Log in using Rosepad >=1.1.0.2-beta to authenticate.
```

**Log (client was not previously authenticated)**:
```
2022-07-23 13:51:48 [INFO] MATCH ULPP1

2022-07-23 13:51:48 [INFO] EXT NAME ULPP VER 1

2022-07-23 13:51:48 [INFO] MATCH ULPP1

2022-07-23 13:51:48 [INFO] EXT NAME ULPP VER 1

2022-07-23 13:51:48 [INFO] MATCH ULPP1

2022-07-23 13:51:48 [INFO] EXT NAME ULPP VER 1

2022-07-23 13:51:48 [INFO] Player1659 [/25.19.133.219:35686] logged in with ULPP1
2022-07-23 13:51:48 [INFO] Player count: 1

2022-07-23 13:51:48 [SEVERE] java.net.SocketException: Connection reset
2022-07-23 13:51:48 [SEVERE]    at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
2022-07-23 13:51:48 [SEVERE]    at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
2022-07-23 13:51:48 [SEVERE]    at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
2022-07-23 13:51:48 [SEVERE]    at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
2022-07-23 13:51:48 [SEVERE]    at java.base/java.net.Socket$SocketInputStream.read(Socket.java:961)
2022-07-23 13:51:48 [SEVERE]    at java.base/java.io.FilterInputStream.read(FilterInputStream.java:82)
2022-07-23 13:51:48 [SEVERE]    at net.minecraft.src.Packet.readPacket(Packet.java:87)
2022-07-23 13:51:48 [SEVERE]    at net.minecraft.src.NetworkManager.readPacket(NetworkManager.java:119)
2022-07-23 13:51:48 [SEVERE]    at net.minecraft.src.NetworkManager.readNetworkPacket(NetworkManager.java:206)
2022-07-23 13:51:48 [SEVERE]    at net.minecraft.src.NetworkReaderThread.run(NetworkReaderThread.java:17)

2022-07-23 13:51:48 [INFO] Player1659 lost connection: Internal exception: java.net.SocketException: Connection reset
2022-07-23 13:51:48 [INFO] Player count: 0

2022-07-23 13:51:48 [INFO] Player1659 lost connection: Internal exception: java.net.SocketException: Connection reset
2022-07-23 13:51:48 [INFO] Player count: 0
```

**Comment by Vladg24YT** [comment]
Closing the issue as it is unlikely that I find a solution to it
