### ISSUE TITLE
Incorrect `ItemStack` handling in `LBInventory`

### ISSUE THREAD

**Issue by Vladg24YT** [Vladg24YT/LilyBukkit#5]
Tried launching LilyBukkit with `WorldEdit 4.7` for CraftBukkit `1240`, got this error when trying to execute `//wand`.

**Log**:
```
2022-07-15 17:09:52 [INFO] [LilyBukkit] Sending a message §cPlease report this error: [See console]
2022-07-15 17:09:52 [INFO] [LilyBukkit] Sending a message java.lang.NullPointerException: Cannot read field "minX" because "this.block" is null
2022-07-15 17:09:52 [SEVERE] java.lang.NullPointerException: Cannot read field "minX" because "this.block" is null

2022-07-15 17:09:52 [SEVERE] 	at ru.vladthemountain.lilybukkit.block.LBBlock.getX(LBBlock.java:147)

2022-07-15 17:09:52 [SEVERE] 	at ru.vladthemountain.lilybukkit.block.LBBlock.getData(LBBlock.java:34)

2022-07-15 17:09:52 [SEVERE] 	at com.sk89q.worldedit.bukkit.BukkitWorld.getBlockData(BukkitWorld.java:172)

2022-07-15 17:09:52 [SEVERE] 	at com.sk89q.worldedit.EditSession.rawGetBlock(EditSession.java:400)

2022-07-15 17:09:52 [SEVERE] 	at com.sk89q.worldedit.EditSession.getBlock(EditSession.java:352)

2022-07-15 17:09:52 [SEVERE] 	at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:251)

2022-07-15 17:09:52 [SEVERE] 	at com.sk89q.worldedit.EditSession.setBlocks(EditSession.java:920)

2022-07-15 17:09:52 [SEVERE] 	at com.sk89q.worldedit.commands.RegionCommands.set(RegionCommands.java:63)

2022-07-15 17:09:52 [SEVERE] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

2022-07-15 17:09:52 [SEVERE] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

2022-07-15 17:09:52 [SEVERE] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

2022-07-15 17:09:52 [SEVERE] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

2022-07-15 17:09:52 [SEVERE] 	at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:428)

2022-07-15 17:09:52 [SEVERE] 	at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:158)

2022-07-15 17:09:52 [SEVERE] 	at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:101)

2022-07-15 17:09:52 [SEVERE] 	at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:421)

2022-07-15 17:09:52 [SEVERE] 	at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:339)

2022-07-15 17:09:52 [SEVERE] 	at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1226)

2022-07-15 17:09:52 [SEVERE] 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:237)

2022-07-15 17:09:52 [SEVERE] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:35)

2022-07-15 17:09:52 [SEVERE] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:129)

2022-07-15 17:09:52 [SEVERE] 	at ru.vladthemountain.lilybukkit.LilyBukkit.dispatchCommand(LilyBukkit.java:484)

2022-07-15 17:09:52 [SEVERE] 	at ru.vladthemountain.lilybukkit.entity.LBPlayer.performCommand(LBPlayer.java:157)

2022-07-15 17:09:52 [SEVERE] 	at net.minecraft.server.MinecraftServer.commandLineParser(MinecraftServer.java:503)

2022-07-15 17:09:52 [SEVERE] 	at net.minecraft.server.MinecraftServer.doTick(MinecraftServer.java:281)

2022-07-15 17:09:52 [SEVERE] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:215)

2022-07-15 17:09:52 [SEVERE] 	at net.minecraft.src.ThreadServerApplication.run(ThreadServerApplication.java:14)
```

**Comment by Vladg24YT** [comment]
Issue resolved
