### ISSUE TITLE
java.lang.IlligalStateException: Entity is already tracked!

### ISSUE THREAD

**Issue by Vladg24YT** [Vladg24YT/LilyBukkit#8]
Tried launching LilyBukkit with `WorldEdit 4.7` for CraftBukkit `1240`, got this error when trying to execute `//set 2`.

**Log**:
```
[INFO] [LilyBukkit] Sending a message §cPlease report this error: [See console]
[INFO] [LilyBukkit] Sending a message java.lang.IllegalStateException: Entity is already tracked!
[SEVERE] java.lang.IllegalStateException: Entity is already tracked!

[SEVERE] 	at net.minecraft.src.EntityTracker.trackEntity(EntityTracker.java:48)

[SEVERE] 	at net.minecraft.src.EntityTracker.trackEntity(EntityTracker.java:24)

[SEVERE] 	at net.minecraft.src.WorldManager.obtainEntitySkin(WorldManager.java:16)

[SEVERE] 	at net.minecraft.src.World.obtainEntitySkin(World.java:796)

[SEVERE] 	at net.minecraft.src.World.addLoadedEntities(World.java:1436)

[SEVERE] 	at net.minecraft.src.Chunk.onChunkLoad(Chunk.java:370)

[SEVERE] 	at ru.vladthemountain.lilybukkit.LBChunk.load(LBChunk.java:136)

[SEVERE] 	at ru.vladthemountain.lilybukkit.LBChunk.load(LBChunk.java:147)

[SEVERE] 	at ru.vladthemountain.lilybukkit.LBWorld.loadChunk(LBWorld.java:269)

[SEVERE] 	at ru.vladthemountain.lilybukkit.LBWorld.loadChunk(LBWorld.java:295)

[SEVERE] 	at com.sk89q.worldedit.bukkit.BukkitWorld.checkLoadedChuck(BukkitWorld.java:685)

[SEVERE] 	at com.sk89q.worldedit.EditSession.rawGetBlock(EditSession.java:397)

[SEVERE] 	at com.sk89q.worldedit.EditSession.getBlock(EditSession.java:352)

[SEVERE] 	at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:251)

[SEVERE] 	at com.sk89q.worldedit.EditSession.setBlocks(EditSession.java:920)

[SEVERE] 	at com.sk89q.worldedit.commands.RegionCommands.set(RegionCommands.java:63)

[SEVERE] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[SEVERE] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

[SEVERE] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[SEVERE] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

[SEVERE] 	at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:428)

[SEVERE] 	at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:158)

[SEVERE] 	at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:101)

[SEVERE] 	at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:421)

[SEVERE] 	at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:339)

[SEVERE] 	at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1226)

[SEVERE] 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:237)

[SEVERE] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:35)

[SEVERE] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:129)

[SEVERE] 	at ru.vladthemountain.lilybukkit.LilyBukkit.dispatchCommand(LilyBukkit.java:518)

[SEVERE] 	at ru.vladthemountain.lilybukkit.entity.LBPlayer.performCommand(LBPlayer.java:157)

[SEVERE] 	at net.minecraft.server.MinecraftServer.commandLineParser(MinecraftServer.java:500)

[SEVERE] 	at net.minecraft.server.MinecraftServer.doTick(MinecraftServer.java:281)

[SEVERE] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:215)

[SEVERE] 	at net.minecraft.src.ThreadServerApplication.run(ThreadServerApplication.java:14)
```

**Comment by Vladg24YT** [comment]
Can't pinpoint the problem, this issue requires more testing.

**Comment by Vladg24YT** [comment]
The problem doesn't seem to be present now. Feel free to reopen the issue if you stumble upon a similar one.
