### ISSUE TITLE
Index `x` out of bounds for length 32768 when changing blocks

### ISSUE THREAD

**Issue by Vladg24YT** [Vladg24YT/LilyBukkit#9]
Used `WorldEdit 4.7`, command `//set 2`

**Log**:
```
[INFO] [LilyBukkit] Sending a message §cPlease report this error: [See console]
[INFO] [LilyBukkit] Sending a message java.lang.ArrayIndexOutOfBoundsException: Index -958 out of bounds for length 32768
[SEVERE] java.lang.ArrayIndexOutOfBoundsException: Index -958 out of bounds for length 32768

[SEVERE] 	at net.minecraft.src.Chunk.getBlockID(Chunk.java:172)

[SEVERE] 	at ru.vladthemountain.lilybukkit.LBChunk.getBlock(LBChunk.java:72)

[SEVERE] 	at ru.vladthemountain.lilybukkit.LBWorld.getBlockAt(LBWorld.java:103)

[SEVERE] 	at com.sk89q.worldedit.bukkit.BukkitWorld.getBlockData(BukkitWorld.java:172)

[SEVERE] 	at com.sk89q.worldedit.EditSession.rawGetBlock(EditSession.java:400)

[SEVERE] 	at com.sk89q.worldedit.EditSession.getBlock(EditSession.java:352)

[SEVERE] 	at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:251)

[SEVERE] 	at com.sk89q.worldedit.EditSession.setBlocks(EditSession.java:920)

[SEVERE] 	at com.sk89q.worldedit.commands.RegionCommands.set(RegionCommands.java:63)

[SEVERE] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[SEVERE] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

[SEVERE] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[SEVERE] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

[SEVERE] 	at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:428)

[SEVERE] 	at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:158)

[SEVERE] 	at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:101)

[SEVERE] 	at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:421)

[SEVERE] 	at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:339)

[SEVERE] 	at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1226)

[SEVERE] 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:237)

[SEVERE] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:35)

[SEVERE] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:129)

[SEVERE] 	at ru.vladthemountain.lilybukkit.LilyBukkit.dispatchCommand(LilyBukkit.java:518)

[SEVERE] 	at ru.vladthemountain.lilybukkit.entity.LBPlayer.performCommand(LBPlayer.java:157)

[SEVERE] 	at net.minecraft.server.MinecraftServer.commandLineParser(MinecraftServer.java:500)

[SEVERE] 	at net.minecraft.server.MinecraftServer.doTick(MinecraftServer.java:281)

[SEVERE] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:215)

[SEVERE] 	at net.minecraft.src.ThreadServerApplication.run(ThreadServerApplication.java:14)
```

**Comment by Vladg24YT** [comment]
New log, same issue:
```
2022-07-16 11:42:24 [SEVERE] java.lang.ArrayIndexOutOfBoundsException: Index -1463 out of bounds for length 32768
2022-07-16 11:42:24 [SEVERE] 	at net.minecraft.src.Chunk.getBlockID(Chunk.java:172)
2022-07-16 11:42:24 [SEVERE] 	at ru.vladthemountain.lilybukkit.LBChunk.getBlock(LBChunk.java:73)
2022-07-16 11:42:24 [SEVERE] 	at ru.vladthemountain.lilybukkit.LBWorld.getBlockAt(LBWorld.java:63)
2022-07-16 11:42:24 [SEVERE] 	at com.sk89q.worldedit.bukkit.BukkitWorld.getBlockData(BukkitWorld.java:172)
2022-07-16 11:42:24 [SEVERE] 	at com.sk89q.worldedit.EditSession.rawGetBlock(EditSession.java:400)
2022-07-16 11:42:24 [SEVERE] 	at com.sk89q.worldedit.EditSession.getBlock(EditSession.java:352)
2022-07-16 11:42:24 [SEVERE] 	at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:251)
2022-07-16 11:42:24 [SEVERE] 	at com.sk89q.worldedit.EditSession.setBlocks(EditSession.java:920)
2022-07-16 11:42:24 [SEVERE] 	at com.sk89q.worldedit.commands.RegionCommands.set(RegionCommands.java:63)
2022-07-16 11:42:24 [SEVERE] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-07-16 11:42:24 [SEVERE] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-07-16 11:42:24 [SEVERE] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-07-16 11:42:24 [SEVERE] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-07-16 11:42:24 [SEVERE] 	at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:428)
2022-07-16 11:42:24 [SEVERE] 	at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:158)
2022-07-16 11:42:24 [SEVERE] 	at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:101)
2022-07-16 11:42:24 [SEVERE] 	at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:421)
2022-07-16 11:42:24 [SEVERE] 	at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:339)
2022-07-16 11:42:24 [SEVERE] 	at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1226)
2022-07-16 11:42:24 [SEVERE] 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:237)
2022-07-16 11:42:24 [SEVERE] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:35)
2022-07-16 11:42:24 [SEVERE] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:131)
2022-07-16 11:42:24 [SEVERE] 	at ru.vladthemountain.lilybukkit.LilyBukkit.dispatchCommand(LilyBukkit.java:514)
2022-07-16 11:42:24 [SEVERE] 	at net.minecraft.server.MinecraftServer.commandLineParser(MinecraftServer.java:300)
2022-07-16 11:42:24 [SEVERE] 	at net.minecraft.server.MinecraftServer.doTick(MinecraftServer.java:283)
2022-07-16 11:42:24 [SEVERE] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:217)
2022-07-16 11:42:24 [SEVERE] 	at net.minecraft.src.ThreadServerApplication.run(ThreadServerApplication.java:14)
```
